### ISSUE TITLE
[FEATURE] Checking for Enkidu "All Fours" state

### ISSUE THREAD

**Issue by FPTheFluffyPawed** [BoltsJ/lancer-speed-provider#1]
Whenever the Enkidu enters the danger zone, its base speed becomes 6. As requested, I filed this feature so that it can not be forgotten to add such an improvement to the proider...

![imagem](https://github.com/BoltsJ/lancer-speed-provider/assets/18551568/0c3651ba-1f59-4679-bc9c-3ae49fad7d5f)

**Comment by BoltsJ** [comment]
Closed in 52c1ea0b92289d67583ff9d43e1b7ca3cd579135
